name: build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: cache poetry install
        uses: actions/cache@v2
        with:
          path: ~/.local
          key: poetry-1.3.1-0
      - uses: snok/install-poetry@v1
        with:
          version: 1.3.1
          virtualenvs-create: true
          virtualenvs-in-project: true
      - name: Install pipx
        run: |
          pip install pipx

      - name: Install global dependencies
        run: |
          pipx install poetry

      - name: Install Dependencies
        run: poetry install --with dev

      - name: Run Makefile
        run: make build

      - name: Upload Package
        uses: actions/upload-artifact@v3.1.2
        with:
          name: packages
          path: dist/
          if-no-files-found: error
          retention-days: 1

